# Generated by Django 4.2.3 on 2023-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.FileField(upload_to='other/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(upload_to='pictures/%Y-%m-%d/'),
        ),
    ]
