# Generated by Django 4.2.3 on 2023-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_author_replies_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.FileField(blank=True, upload_to='other/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pictures/%Y-%m-%d/'),
        ),
    ]
