# Generated by Django 4.2.3 on 2023-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_other_alter_post_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='other',
        ),
        migrations.RemoveField(
            model_name='post',
            name='other',
        ),
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
